package de.torsm.socks.protocol

import org.junit.jupiter.api.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals

/**
 * Hand-authored RFC 1928 section 7 hex vector.
 *
 * Assembled independently from the field layout at
 * https://www.rfc-editor.org/rfc/rfc1928#section-7. Not generated by any SOCKS tool.
 * Validity is guaranteed by byte-for-byte match with expected fields
 * (RSV=0x0000, FRAG=0x00, ATYP=0x01, DST=192.0.2.1:8080).
 * Replaces the Wireshark check from the old spec (A-F13).
 */
class SocksUdpHeaderRfcVectorTest {

    private val vector = byteArrayOf(
        0x00.toByte(), 0x00.toByte(),
        0x00.toByte(),
        0x01.toByte(),
        192.toByte(), 0x00.toByte(), 0x02.toByte(), 0x01.toByte(),
        0x1F.toByte(), 0x90.toByte(),
        0x48.toByte(), 0x49.toByte(),
    )

    @Test
    fun `hand-authored section 7 IPv4 vector parses to 192_0_2_1 port 8080 payload HI`() {
        val parsed = SocksUdpHeader.parse(vector, vector.size)
        assertEquals("192.0.2.1", parsed.destination!!.address.hostAddress)
        assertEquals(8080, parsed.destination!!.port)
        assertContentEquals(byteArrayOf(0x48.toByte(), 0x49.toByte()), parsed.payload)
    }

    @Test
    fun `hand-authored vector round-trips through wrap`() {
        val dst = java.net.InetSocketAddress(
            java.net.Inet4Address.getByName("192.0.2.1") as java.net.Inet4Address, 8080
        )
        val rewrapped = SocksUdpHeader.wrap(dst, byteArrayOf(0x48.toByte(), 0x49.toByte()))
        assertContentEquals(vector, rewrapped)
    }
}
